# Generated by Django 3.2.6 on 2021-09-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_about_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='what_we_do',
            name='content',
            field=models.TextField(),
        ),
    ]
